In [43]:
import pandas as pd

test_data = pd.read_csv("Data/train.csv")
len(test_data)

test_data.columns
columns = test_data.columns.tolist()
test_data.iloc[:,3:5]
new_data = test_data[[columns[2]] + columns[3:8]]
new_data

,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality
0,8,5,8,6,4,4
1,7,4,4,8,8,3
2,5,6,7,3,7,1
3,4,6,5,4,8,4
4,3,2,6,4,4,3
...,...,...,...,...,...,...
1117952,3,4,10,4,5,5
1117953,2,4,3,9,5,8
1117954,3,9,4,6,5,9
1117955,3,3,7,5,2,3
1117956,5,6,9,5,5,2